- tests/includes/utilities.inc
Instead of one getting purged and then deleteUserCreatedObjects saying kthxbai
> Fix so that all user-generated objects are purged

- includes/breadcrumb.inc
Fixes missing legacy predicate, restores "order by" and adds compound object predicate to  #574
> Restored isPartOf, order by, added comp. predicate

- includes/tuque_wrapper.inc
- tests/includes/utilities.inc
This is a bug fix for some 409s.  It's pretty low level though and carries more risk than I'd like to see added to a release this close.  I'm not sure we should create a release pull.
> 7.x.more 409s

- includes/delete_datastream.form.inc
Added checkbox for option to delete derivatives from datastream.
> Added checkbox for option to delete derivatives from datastream.

- css/islandora.objects.css
- islandora.api.php
- islandora.module
- theme/islandora-objects-grid.tpl.php
- theme/theme.inc
"islandora_objects" takes the full array, which could blow up memory, so let us pass paging parameters and a page of values instead.
> Implement "islandora_objects_subset".

- .travis.yml
- tests/scripts/travis_setup.sh
See: https://jira.duraspace.org/browse/ISLANDORA-1149
> Add fcrepo 3.8.1 support. Address ISLANDORA-1149

- includes/admin.form.inc
- islandora.install
Created a config variable so that you can make the OBJ upload optional, if you so desire.
> ISLANDORA-1362 Put config variable in admin form.

- includes/solution_packs.inc
**Jira:** [ISLANDORA-1586](https://jira.duraspace.org/browse/ISLANDORA-1586) 
Simplify object existence check.
Uninstall (not just disable) an installed solution pack module, and the message about [any installed objects from the given solution pack](https://github.com/adam-vessey/islandora/blob/7.x-ISLANDORA-1586/includes/solution_packs.inc#L487-L493) should be emitted.
* **Does this change require documentation to be updated?** No.
* **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No
* **Could this change impact execution of existing code?** Unlikely. 
**Tagging:** @jordandukart (as maintainer)
----
Adam Vessey
_Developer_
**[discoverygarden …
> Change existence check to use islandora_object_load().

- README.md
Updates the readme to correct some links, make a small formatting change, and add current Maintainer information as part of the 7.x-1.7 audit.
* Review the changes to the text
* Test the new links to verify they go where they should
* Compare the Maintainers listed to those listed on the [release team spreadsheet](https://docs.google.com/spreadsheets/d/1PRv2Xo-sNE_sDJHUT5OvTXmNiSHnkdJgwo7VsFkIUgY)
* **Does this change require documentation to be updated?** This change _is_ an update of documentation :smile: 
* **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No.
* **Could this change impact execution of existing code?** No.
* **Does this require a pull request on the …
> Update README.md for 7.x-1.7

- README.md
Updates the Maintainer as part of the 7.x-1.8 Release Audit.
> Update README.md - Update Maintainer

- README.md
Updates the Maintainer list.
@DiegoPino
> Update README.md - Release branch

- islandora.module
- theme/islandora-object-overview.tpl.php
- theme/theme.inc
**JIRA Ticket**: (https://jira.duraspace.org/browse/ISLANDORA-1762)
Lists the content models associated with each Islandora object in the overview tab.
Like it says on the tin.
View any Islandora object, navigate to Manage/Overview
> Add content model to object overview

- includes/tuque_wrapper.inc
**JIRA Ticket**: 
Super minor change, I don't believe it needs a JIRA ticket.
Fix a minor typo in the `tuque_wrapper.inc` doc comment.
@DiegoPino
> Fix minor typo

- includes/ingest.form.inc
**JIRA Ticket**: (https://jira.duraspace.org/browse/ISLANDORA-1832)
Add context, or content model label, to the top of islandora_ingest_form.
Because of the way ingest forms are constructed, in steps, i have added a form alter to add the content model label at the top of the islandora_ingest_form
During the ingest of any object using the islandora_ingest_form, the content model's label should appear at the top of the ingest form.
Tag @DiegoPino
> Added context info to ingest forms.

- CONTRIBUTING.md
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1698
* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
Added copy and link to the new code of conduct.
@manez  @Islandora/7-x-1-x-committers
> ISLANDORA-1698 - update contributing.md

- theme/theme.inc
Release version of this pull: 
https://github.com/Islandora/islandora/pull/670
> Islandora-1943

- README.md
- includes/tuque_wrapper.inc
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1995
Fixes a bad replacement in a previous PR https://github.com/Islandora/islandora/pull/678.
Correct replacement.
Relates to: https://github.com/Islandora/islandora_solution_pack_collection/pull/191 and https://github.com/Islandora/tuque/pull/157
> DSID not datastream.

- README.md
ISLANDORA-7.x-1.10 Release
What does this Pull Request do?
Changed the maintainer from Diego Pino to Will Panting on the README.md .
What's new?
Will Panting is the maintainer. 
Additional Notes:
Tag (@ mention) interested parties or, if unsure, @Islandora/7-x-1-x-committers
> Updated README.md maintainer

- theme/theme.inc
Release PR for https://github.com/Islandora/islandora/pull/688
> ISLANDORA-2064: Object context for permission check.

- README.md
Maintainer update for release 7.x-1.11.
**JIRA Ticket**: n/a
Changed maintainer to Diego Pino, fixed HTTP/HTTPS URL and removed extra whitespace.
- Changed maintainer to Diego Pino
- changed the scheme in a GitHub URL to HTTPS
- Removed whitespace at the end of lines (no change to layout visible)
n/a
(C)CLA has been signed and submitted by my employer.
Old maintainer: @willtp87 ; new maintainer: @DiegoPino
> Update module maintainer in README, use HTTPS for GitHub

- includes/datastream.inc
Release pull for https://github.com/Islandora/islandora/pull/704
> Prevent Warning [Release Pull]

- README.md
Adds @jonathangreen to the maintainer list.
@Islandora/7-x-1-x-committers @jonathangreen @DiegoPino
> Adds Jon Green to README maintainer list

- includes/solution_packs.inc
- tests/scripts/run_tests.sh
- tests/scripts/travis_scripts.sh
**JIRA Ticket**: n/a
Related to https://github.com/Islandora/islandora_solution_pack_audio/pull/148#issuecomment-462811400
Wraps the input to the `run_tests.sh` to ensure labels like Islandora Audio get captured correctly.
Also as some basic output of what is being run to ensure we are running the correct stuff.
Let Travis run, but carefully inspect the results to ensure a pass is really a pass.
@Islandora/7-x-1-x-committers, specifically @DiegoPino and @jonathangreen
> fix test runner and document travis scripts

- includes/regenerate_derivatives.form.inc
**JIRA Ticket**: N/A
Fixes a typing issue introduced in https://github.com/Islandora/islandora/pull/714.
@whikloj
> Type as bool.

- includes/dublin_core.inc
- includes/mime_detect.inc
- includes/tuque_wrapper.inc
- includes/utilities.inc
- tests/includes/utilities.inc
PRs are currently failing because of an update in the 3.6 version of the coding standards module. This adds some doc comments to make dcs happy again.
Review added comments to make sure they look accurate. Make sure travis goes green.
@DiegoPino @whikloj
> Fix islandora for latest 3.6 coding standard update.

- islandora.module
Hey just found some errors in comments. Hope it's ok to PR without an issue.
> Copy-pasta errors.

- src/Plugin/Condition/MediaHasMimetype.php
**JIRA Ticket**: none
Changes the display name "Media has Mime Type" to "Node has Media with Mime Type" because for a long time we thought it was broken, until we read the code which makes very clear that it
```
* Provides a condition based on a node's media's MimeType.
*
* Note that this condition applies when the parent node is viewed.
```
This should be clear in the interface.
pull, clear cache, add a condition to a context.
Needs doc updates.
Sister pull request coming for documentation wiki.
Tag (@ mention) interested parties or, if unsure, @Islandora/7-x-1-x-committers
> Change condition name to be explicitly a node condition.

- src/Flysystem/Fedora.php
**Ticket**: https://github.com/Islandora/documentation/issues/1396
Catches GuzzleExceptions when attempting to ping Fedora to ensure they are caught and reported on.
1. Bring up a playbook
1. Goto http://localhost:8000/admin/reports/status
1. See the Status Report
1. Shutdown tomcat (`sudo service tomcat8 stop`)
1. Reload the Status Report
1. See White Screen of Death.
1. Pull in this PR.
1. Reload the Status Report
1. See the Status report with section **Errors Found** containing
`Flysystem: fedora     http://127.0.0.1:8080/fcrepo/rest/ is unavailable, cannot connect.`
> Catch Flysystem exceptions and report

- composer.json
**Github Ticket**: [#1472](https://github.com/Islandora/documentation/issues/1472) Update drupal/jwt to 8.x-1.0-beta1 #1472
Updates JWT module to latest stable version, adds new 'Administer JSON Web Token module' permission (automatically assigned to users with administration role).
* Apply PR
* composer update drupal/jwt
* drush cr
* create a sample Repository Item, model=Image with attached image Media, with Media Use=Original File, observe (a) correct generation of Service File and Thumbnail Image derivatives, and that original file is stored in fcrepo with out errors in watchdog, etc.
> #1472 Update drupal/jwt to 8.x-1.0-beta1

- composer.json
**Github Ticket**: [#1497](https://github.com/Islandora/documentation/issues/1497) Update drupal/jwt to 8.x-1.0-beta2 #1497
Updates JWT module to latest stable version, adds new 'Administer JSON Web Token module' permission (automatically assigned to users with administration role).
* Apply PR
* composer update drupal/jwt
* drush cr
* create a sample Repository Item, model=Image with attached image Media, with Media Use=Original File, observe (a) correct generation of Service File and Thumbnail Image derivatives, and that original file is stored in fcrepo with out errors in watchdog, etc.
> #1497 Update drupal/jwt to 8.x-1.0-beta2

- composer.json
**Github Ticket**: https://github.com/Islandora/documentation/issues/1560
Alter Islandora `composer.json` to reference JWT 8.x-1.0-beta5
A brief description of what the intended result of the PR will be and/or what problem it solves.
Minor update of JWT module.
* Apply PR. 
* composer update drupal/jwt
* *no drush updb needed*
* drush cr
* perform an action requiring authentication via JWT, e.g. create thumbnail for image, confirm correct operation.
@seth-shaw-unlv @manez
> #1560 Update JWT to 8.x-1.0-beta5
