islandora.module

Drupal's page caching offers a substantial speed up, so let's establish some invalidation to let us use it.
We try to hit the cases where objects (and datastreams) are ingested, modified or purged via Drupal's GUI, assuming that people running drush batches can `drush cc all` as appropriate.
With this pull request, we clear the cache in response to events triggered from forms or batches--other mechanisms which may make modifications are currently expected to clear the cache.
There may be some other places we wish to look into invalidating the cache, such as:
* Islandora Solr Metadata
* Islandora Solr Views
* Viewer configuration pages in general

Page cache invalidation.

---

includes/solution_packs.inc

https://jira.duraspace.org/browse/ISLANDORA-1461
Check the description there for details, but the core of it is that we shouldn't be checking that the XML is well-formed when Solution packs required objects is just getting the diff to see if the datastream has changed. It's not the job of that page to validate XML; XML should be validated when it is going to be used.

Don't need to check for properly-formed XML when just getting the diff

---

includes/tuque_wrapper.inc

Addresses https://jira.duraspace.org/browse/ISLANDORA-1522
Added local methods(override) to handle global UUID settings. Changed
default valued for $create_uuid to NULL to allow developers to override
the global setting if needed.
This pull is part of a series of other pulls to make this change apply
to other modules

ISLANDORA-1522 global UUID setting enforcement

---

includes/datastream.inc
includes/utilities.inc
islandora.api.php
islandora.module
theme/theme.inc

**Jira:** https://jira.duraspace.org/browse/ISLANDORA-1547
Adds a drupal_alter to allow for modification to the datastream edit registry.
Pull down the pull both the islandora (core) pull request and the islandora_xml_forms pull request.
Test 1: Confirming the addition of an custom index value does not impact form loading.
Edit an existing object's datastream the process should function the same as before the pull and load
the registry item built in xml_form_builder_islandora_edit_datastream_registry. 
Test 2: Testing the drupal_alter.
Have a module implement hook_islandora_edit_datastream_modify_registry_alter() and test making changes to the edit_registry.
1) Adding an edition registry item - this should load the default switch logic so that multiple routes are rendered.
2) Removing …

ISLANDORA-1547

---

includes/admin.form.inc
includes/tuque_wrapper.inc
islandora.install

**Jira:** [ISLANDORA-1556](https://jira.duraspace.org/browse/ISLANDORA-1556)
The purpose of this pull request is to configurably take over as much control of object concurrency as possible as Fedora has some issues with this.
The pull request is using Drupal semaphores as they are quite powerful and already available.
This is difficult to test but there are many ways to cause the issue.  One must set up a situation where Islandora is modifying the same object from two different processes. Without this feature enabled there will be intermittent and inconsistent issues in Fedora.  After this change these should be greatly reduced.
Please see [ISLANDORA-1556](https://jira.duraspace.org/browse/ISLANDORA-1556) for some examples.
This is a general issue but has become more pressing as some …

Optionaly using semaphores on APIM.

---

theme/theme.inc

**Jira:** https://jira.duraspace.org/browse/ISLANDORA-1576
Add the pid to the return array of the 'islandora_object_mapper' utility function.
To test this one may enable SOLR as the default display generation,{SITE}/admin/islandora/solution_pack_config/basic_collection, implement a preprocess function for  grid or list ({MODULE/THEME}_preprocess_islandora_objects_grid($&vars)), and dd out the results (or dsm(), utilizing devel).
<Provide any background context relating to this pull request, this could be IRC logs, discussion on the list, email communication, etc. Basically anything you have that adds additional information as to why this pull request is being proposed>
It would be useful to add an objects PID to the return result of the utility funciton …

Adding pid to object_mapper utility

---

includes/tuque_wrapper.inc
islandora.api.php

**Jira:** [ISLANDORA-1590](https://jira.duraspace.org/browse/ISLANDORA-1590)
Adds an alter invocation to permit the configuration of presently-unavailable Tuque connection parameters.
Implement the hook and set some of the parameters... A module has been created to do this: [islandora_repository_connection_config](https://github.com/discoverygarden/islandora_repository_connection_config): [implementation](https://github.com/discoverygarden/islandora_repository_connection_config/pull/1)
* **Does this change require documentation to be updated?** No? (updated the relevant api.php)
* **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No.
* **Could this change impact …

Make Tuque connection parameters available for configuration

---

includes/object_properties.form.inc
islandora.module

**Jira:** <https://jira.duraspace.org/browse/ISLANDORA-1596> 
Removes unneeded calls to the breadcrumb functions that are being called previously in the menu router.
View an object and any and all of the tabs underneath it. Note how the title and breadcrumbs stay the same as they were before.
Reduce the amount of times we are performing requests out against resources.
* **Does this change require documentation to be updated?** No.
* **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No.
* **Could this change impact execution of existing code?** Any modules that call islandora_view_object directly will need to set their own title within the callback such as compound.
As …

Remove extra breadcrumb and set title calls.

---

islandora.module

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1696
* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/islandora-dev/8eSxcOtSlX4/pw_VAFZbAgAJ
Removes the download_clip endpoint from the Islandora core module as only solution packs using OpenSeadragon use it and the offending callback function.

Remove unneeded download path and clip function.

---

includes/derivatives.inc
includes/tuque_wrapper.inc
islandora.api.php
islandora.module
tests/derivatives.test
tests/hooks.test
tests/islandora_derivatives_test.module
tests/islandora_hooks_test.module

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1755
Addresses [this TODO](https://github.com/Islandora/islandora/blob/ab520433c72365b69cfd1804a749e64d27adc853/islandora.api.php#L261) recommending that the FedoraDatastream::modifyDatastream parameters be passed through the datastream_modified hook to provide additional context for its implementations.
It also passes those parameters through to derivative generation hooks so that derivative generation can be aware of what was modified before attempting to do that generation.
Mostly additions to `islandora.api.php`; some new parameters in datastream_modified and derivative hooks' function signatures. It's been done in a way that's as non-destructive as possible.
Also some bubbling up of parameters from the tuque wrapper.
While …

update API to include DS modified params

---

theme/islandora-dublin-core-description.tpl.php
theme/theme.inc

**JIRA Ticket**:
https://jira.duraspace.org/browse/ISLANDORA-1839
This pull request adds a call to `nl2br` and `filter_xss` to the default metadata description template. This allows new lines in the Dublin Core to be preserved when displaying the description to the user.
- added call to `nl2br` to add <br> so that new lines are displayed with the description
- added call to `filter_xss` to make the metadata description tempalte the same as the default metadata template, and to ward off any nasty XSS.
- Create new object, add new lines in description field in the metadata. 
- Check that isn't displayed before pull request
- Check that new lines are displayed once pull request is used
- Create object without newlines
- Check that description does not change.
Should be fairly minor change. …

Update default dublin core template

---

theme/theme.inc

**JIRA Ticket**:
https://jira.duraspace.org/browse/ISLANDORA-1839
* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
https://github.com/Islandora/islandora/pull/657
This is a slight amendment of the pull request mentioned above. @jordandukart noticed that its possible that `$variables['dc_array']` is an empty array, and so my previous pull request would cause a warning. This should fix that case.
Fixes a possible warning.
Make sure there is still a description shown when using the DC metadata display. 
@jordandukart @adam-vessey @DiegoPino

Changed based on code review to pull #657

---

README.md
includes/admin.form.inc
includes/breadcrumb.inc
islandora.api.php
islandora.install
islandora.module

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1724
This PR allows other modules to implement a hook to replace the default generation of breadcrumbs with whatever method they wish. It adds an admin form space to choose which implementation to use.
- Adds a new hook `hook_islandora_breadcrumbs_backends` to add a custom breadcrumb method.
- Adds a new section to the Islandora admin form to choose which breadcrumb method to use.
- Makes the current method of `islandora_get_breadcrumbs()` invoke the above hook and based on the above Admin form selection invoke that callback function.
- The existing `islandora_get_breadcrumbs_recursive()` Sparql function remains and is the default method.
If everything works as expected this PR should have no effect, unless you create a module …

7.x islandora 1724

---

includes/admin.form.inc
includes/ingest.form.inc
islandora.install

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1876
https://github.com/Islandora/islandora/pull/656
https://github.com/Islandora/islandora_solution_pack_newspaper/pull/146
Fixes failing TRAVIS-CI tests on Newspaper and Book solution packs after a small bug introduced by https://github.com/Islandora/islandora/pull/656 that i, myself, merged 😢. Also adds a drupal variable to enable/disable this contextual titles in ingests steps.
Nothing really. Just fixing a merge i should have tested in more details. And allowing also previous existing functionality (like no CMODEL titles in forms) to co-exist.
There are two ways: After this changes, all non collection based ingest steps(book pages, newspaper issues, should not throw errors anymore. Also Drupal automated test suits for those …

Fixes incorrect assumption

---

css/islandora.base.css
css/islandora.objects.css

**JIRA Ticket**: (https://jira.duraspace.org/browse/ISLANDORA-1870)
Basic fix for SPARQL and SOLR thumbnail display width.
Add a max-width to thumbnails using the SOLR Backend display
Example:
* Added .islandora-object img max-width rule
* Add a large .png as a thumbnail for an object (large as in 'width')
* View object in a collection grid using the SOLR backend display (maintains aspect)
* View object in a collection grid using SPARQL Legacy display (maintains aspect) 
Related in part to this ticket: https://jira.duraspace.org/browse/ISLANDORA-1609, i believe the ultimate solution is to ensure both displays are run thru the same preprocess functions, using the same HTML and CSS as each other. However, that may be to dramatic of a change outside of a major release. 
Tag …

7.x solr thumbnail

---

.travis.yml

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1880
Replaces Travis-CI Drupal Test invocations made via Drush, which are being deprecated, with Drupal's provided PHP scripts. Updates the YAML to have a MySQL timeout so that long running tests don't cause the MySQL session to timeout. Lastly, adds sudo for the YAML as old builds were grandfathered.
Modified the .travis.yml  file from Drush to the drupal script. Added Sudo in .travis.yml file as it required for the scrips to run, repos before 2015 were grandfathered in. However, this isn't the case for forks. Also, added a before_script in travis.yml file to extend mysql wait time to 1200 as the builds were failing in Travic-ci.org. 

7.x islandora 1880

---

theme/theme.inc

**JIRA Ticket**: 
https://jira.duraspace.org/browse/ISLANDORA-1943
Update the datastream table so that it doesn't end up with missing columns if you don't have certain permissions. As the function currently works you can end up with a datastream table that looks like this:
Update the function to insert blank columns where appropriate, instead of skipping them all together.
- Enable embargo module
- Ingest an item
- Add an embargo to the item where your IP is not in the IP range
- Go to item as admin user and check datastream table
Before pull the table should be broken as above. After pull the table should be complete.
@DiegoPino

ISLANDORA-1943

---

islandora.api.php

**JIRA Ticket**: [ISLANDORA-1928](https://jira.duraspace.org/browse/ISLANDORA-1928)
Updates the hook name declarations in islandora.api.php
- s/[hook_cmodel_pid_islandora_datastream_modified](https://github.com/Islandora/islandora/blob/7.x/islandora.api.php#L356)/hook_cmodel_pid_dsid_islandora_datastream_modified/
- s/[hook_cmodel_pid_islandora_datastream_purged](https://github.com/Islandora/islandora/blob/7.x/islandora.api.php#L380)/hook_cmodel_pid_dsid_islandora_datastream_purged/
Notice the addition of "_dsid" after "hook_cmodel_pid" in each function name.
Implement the hooks as documented and they never get triggered. Implement them with the DSID in the function name and they do.
This was discovered after a long struggle with [these …

ISLANDORA-1928: Updates erroneous hook names in islandora.api.php

---

islandora.api.php
tests/islandora_derivatives_test.module

JIRA Ticket: https://jira.duraspace.org/browse/ISLANDORA-1960
https://github.com/Islandora/islandora_checksum/pull/52
Allows derivative alter hooks to exist which don't depend or even use Objects. 
At API level, it is more a convention than something enforced. But anyway needed.
The reason for this is that derivatives as they are defined in Islandora Land are not bound to an Islandora Object, its existence or even its execution context.
This allows for third party modules to invoke and alter derivatives if needed (for example to fetch all possible derivatives for a given Content Model) without having to pass an abstract Object.
Really nothing to test here. The whole idea is to match the function signature of the derivative hook. If the main one does not require an Object to be present, …

ISLANDORA-1960 Allow NULL abstract object in derivative alter hook

---

islandora.module

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1983
* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
https://groups.google.com/d/msg/islandora/jyvEbFjmnIk/soutnsLlBgAJ
Does not use a constant that isn't available in earlier PHP.
@DiegoPino

Don't use a constant not defined in earlier PHPs.

---

theme/theme.inc

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1071
This pull request ensures that when a function in this module implements hook_theme() that the template_preprocess hook is called to allow overriding variables further down the processing chain.
Three function names have been changed to begin with ‘template’ instead of islandora.

7.x islandora 1071

---

islandora.module

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1781
Related ticket that this is the documentation fix for: https://jira.duraspace.org/browse/ISLANDORA-1776
Notifies the user that the object they're looking at is not active.
A drupal_set_message ("warning") in islandora_view_object().
Set an object as "Inactive" or "Deleted" (under Manage > Properties). Load the object, and you should see this warning. If you have Solr metadata enabled, watch as the metadata vanishes as this object is removed from the index. 
Changes to the wording welcome. There is scarce documentation about the "Inactive" and "Deleted" states, so there is no place to change documentation, but that is another issue in itself: https://jira.duraspace.org/browse/ISLANDORA-1985 
@Islandora/7-x-1-x-committers and …

ISLANDORA-1781 display that an object is not active.

---

includes/tuque_wrapper.inc

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1995
Updates the exception catcher around the ingestDatastream call to be correct and provide some more info. Previously Tuque would return `FALSE` when ingestDatastreams were not successful and would attempt to invoke the `islandora_datastream_ingested` hooks on datastream objects that did not exist.
In https://github.com/Islandora/tuque/pull/157 a new exception is being thrown when we attempt to ingest a datastream to an object that already has that datastream. This corrects the text around the messaging.
Enable the test module from: https://github.com/jordandukart/datastream_ingest_test
Re-ingest a collection that defines a TN from the required objects solution packs page (admin/islandora/solution_pack_config/solution_packs) …

Use the replacements and less pasta.

---

theme/theme.inc

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1998
* Discussion in Islandora Mailing List: https://groups.google.com/forum/#!topic/islandora/E0q3e-ZiK7Q 
Checks the right permission when deciding whether to show "Replace" datastream link.
ISLANDORA_REPLACE_DATASTREAM_CONTENT
A description of what steps someone could take to:
* Give a user permission to replace datastreams, but not to view datastream history.
* Before this PR: That user can't replace datastreams in [object]/manage/datastreams.
* After this PR: That user sees the 'Replace' links and can replace a datastream.
@jordandukart or @Islandora/7-x-1-x-committers

ISLANDORA-1998 Check correct permission for replace ds link.

---

includes/mimetype.utils.inc

ISLANDORA-2001 Adds JSON-LD MIME type to islandora_mime_mapping function.
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2001
Adds the [JSON-LD MIME type](https://www.w3.org/TR/json-ld-syntax/#iana-considerations) to the `islandora_mime_mapping` function.   The result is that when downloading a JSON-LD datastream through the datastream management interface, the proper .jsonld extension will be added to the downloaded file (rather than .bin).
Any JSON-LD datastreams with the proper MIME type will be downloaded with the .jsonld file extension when downloading through the manage datastreams interface.
* Review the changed file for syntax errors that may cause PHP notices, warnings or errors.  
* Optional: If you have access to an Islandora instance that has objects with JSON-LD …

ISLANDORA-2001 Adds JSON-LD MIME type to islandora_mime_mapping function.

---

.travis.yml

**ISLANDORA-2053**: (https://jira.duraspace.org/browse/ISLANDORA-2053)
http://irclogs.islandora.ca/2017-09-05.html
https://github.com/travis-ci/travis-ci/issues/2963
As of September 2017, Travis-CI has removed support for PHP 5.3 (and 5.2) for their Ubuntu Trusty Images, forcing us, in order  to keep Drupal's compatibility matrix tested, to run Travis-CI test for 5.3 on Ubuntu Precise
This pull Fixes our failing Travis-CI tests: 
Should allow PHP 5.3.3 to run under Ubuntu Precise and Higher versions under Ubuntu Trusty.
Changes the way we define which PHP versions and Fedora ones run in Travis
We moved PHP 5.3.3 version and the corresponding Fedora versions into the matrix section of the Travis YAML file. 
Travis-CI should pass and everything single PHP/FEDORA version combination should …

ISLANDORA-2053: Update travis.yml to force PHP 5.3.3 to run under Ubuntu Precise

---

includes/admin.form.inc
includes/object_properties.form.inc
islandora.install
islandora.module

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1985
* See also discussion at: https://github.com/Islandora/islandora/pull/676
Blocks access to inactive or deleted objects unless you have special permission.
Added a new Drupal permission. Changed the implementation of hook_islandora_object_access to check for this permission.
Set an object to "Inactive" or "Deleted". Notice that before this PR, anyone with "View repository objects" permission can see this object.
Apply this PR, then give yourself (or other administrator role) the ability to "Access inactive or deleted objects". See that other users who can "View repository objects" can no longer see the deleted/inactive object. 
This'll probably lead to some admin users getting locked out of objects they should see. Not sure …

ISLANDORA-1985 Add a permission to access inactive or deleted objects.

---

islandora.module

**JIRA Ticket**: [ISLANDORA-2043](https://jira.duraspace.org/browse/ISLANDORA-2043)
A check has been added to see if the PID passed to `islandora_object_load()` is malformed when tuque fails to load it, returning a 404 instead of a 403.
- Calls `islandora_is_valid_pid()` when `islandora_object_load()` catches an exception from tuque, and logs a watchdog error noting the offending PID.
Try to load malformed pids via `/islandora/object/<PID>` and check `/admin/reports/dblog` after.
The following malformed PIDs were tested:
- `islandora` (returned a 404 originally but was not logged, now it is)
- `islandora:` (returned a 404 originally but was not logged, now it is)
- `islandora:*`
- `islandora:test*ing`
- `islandora:islandora;`
- `islandora:islandora:islandora`
While PIDS with two colons …

Adds check for invalid PIDs to islandora_object_load fails

---

islandora.module

**JIRA Ticket**: [ISLANDORA-2043](https://jira.duraspace.org/browse/ISLANDORA-2043)
This is a release branch PR for https://github.com/Islandora/islandora/pull/689.
A check has been added to see if the PID passed to `islandora_object_load()` is malformed when tuque fails to load it, returning a 404 instead of a 403.
- Calls `islandora_is_valid_pid()` when `islandora_object_load()` catches an exception from tuque.
Try to load malformed pids via `/islandora/object/<PID>` and check `/admin/reports/dblog` after.
The following malformed PIDs were tested:
- `islandora` (returned a 404 originally)
- `islandora:` (returned a 404 originally)
- `islandora:*`
- `islandora:test*ing`
- `islandora:islandora;`
- `islandora:islandora:islandora`
While PIDS with two colons (eg, …

Release PR for ISLANDORA-2043

---

theme/theme.inc

**JIRA Ticket**: [ISLANDORA-2064](https://jira.duraspace.org/browse/ISLANDORA-2064)
Add more context to access check, permitting overrides.
* Use `islandora_object_access()` instead of `user_access()` for access control to allow things to be influenced from our access hooks.
Primarily, regression testing: Things should work as they did.
Simple test module exposing a block allowing the permissions to be denied via our hooks: https://github.com/adam-vessey/islandora_2064_test
* **Does this change require documentation to be updated?** No.
* **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No.
* **Could this change impact execution of existing code?** Unlikely, but it _is_ …

Object context for permission check.

---

includes/datastream.inc

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2084
Fixes an issue where a byte range request on a redirect datastream would never resolve.
When requesting the view of a redirect datastream with a byte range request the location header is now set as opposed to failing to resolve with a 416.
Follow the instructions in the JIRA ticket.
Example:
* Does this change require documentation to be updated? No.
* Does this change add any new dependencies?  No.
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?  No.
* Could this change impact execution of existing code? No, as the current behavior does not work.

Handle redirects in a proper way.

---

includes/admin.form.inc
includes/object_properties.form.inc
islandora.module

This reverts commit 4f3aefd5ecf222173ce0a66bbc22767aabe9597c. It did not work, and
to make it work requires fixing an underlying issue of datastream permissions being
independent from object permissions.
**JIRA Ticket**: This undoes the problematic fix for https://jira.duraspace.org/browse/ISLANDORA-1985
because of https://jira.duraspace.org/browse/ISLANDORA-2073 
and discussion on https://github.com/Islandora/islandora/pull/685
Removes the permission to view inactive and deleted objects (but leaves it in the uninstall hook, since it was added before code freeze). 
Ensure the new permission is not listed, the toggle is not available, and a user with "view fedora objects" permissions can directly navigate to (and see) an inactive or deleted object. 
Any additional information that you …

Revert "ISLANDORA-1985 Permission to access inactive or deleted"

---

includes/delete_datastream.form.inc

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2119
When a derivative that has an equivalent source_dsid and destination_dsid the delete datastream form does not render as there's non-terminating recursion.
The form renders successfully when this case is encountered.
Define a derivative hook implementation defined with the source_dsid and destination_dsid being equivalent (https://gist.github.com/jordandukart/b488ea8bdfe62a90754f9578ece1acb0 for an example).
If using the example Gist create a new datastream 'TEST' using the txt file as the content by going to /islandora/object/pid/manage/datastreams/add.
Navigate to /islandora/object/pid/datastream/TEST/delete
Note that you get a white screen with a recursion error.
Pull code attempt again, things work as expected. …

Handle derivatives of itself.

---

islandora.module

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2073
* Other Relevant Links 
Formerly https://github.com/Islandora/islandora/pull/685 (wherein it was decided to re-work the logic)
Recently bumped in the Google Group: https://groups.google.com/forum/#!topic/islandora/OUVL7Mc7cmM
Makes datastreams inaccessible unless the object their attached to is accessible.
Logic in the datastream access function now:
* requires at least one TRUE in the results of calling hook_islandora_datastream_access() (formerly required one or more TRUE in either hook_islandora_datastream_access() OR hook_islandora_object_access()) 
*  requires no FALSE in the results of calling hook_islandora_object_access(). (formerly allowed FALSEs in the object access results) 
Implement …

ISLANDORA-2073 Don't allow datastreams if object is forbidden.

---

islandora.module

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2166
Validates that a datastream/object objects are accessible before validating a token present in a datastream view.
Fixes a warning.
- Ingest a large image
- Set a viewing restriction on the object to admin
- Ensure warnings are enabled on the box
- Attempt to view the JP2 directly with a bogus token as the anonymous user, such as:
yoursite/islandora/object/yourpid/datastream/JP2/view?token=garbage
- Warning pops, disappears after the pull.

Ensure object/ds are accessible before verifying token.

---

includes/datastream.version.inc
includes/mimetype.utils.inc

**JIRA Ticket**: [ISLANDORA-2153](https://jira.duraspace.org/browse/ISLANDORA-2153)
* Other Relevant Links
- https://groups.google.com/forum/#!topic/islandora/MqELsn1p0cU
- https://github.com/Islandora-Labs/islandora_binary_object/issues/29
Allows unrestricted MIME type datastream replacement for those DSIDs/CMODELs that allow so. It fixes a problem with [```function islandora_get_extensions_for_datastream(AbstractObject $object, $dsid)```](https://github.com/Islandora/islandora/blob/7.x/includes/mimetype.utils.inc#L75) that returns only the already in place datatream's MIME type if no restrictions in the DS-COMPOSITE-MODEL are found for a given datastream, forcing people to stick to its initial ingest choice in SP like Binary Object (Where OBJ is on purpose left unrestricted).
Means you …

ISLANDORA-2153: Allow datastreams with no MIME type restrictions to be replaced with any file type 

---

includes/orphaned_objects.inc
islandora.module

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2130
Adds new functionality to the Reports menu: lists orphaned objects (children with nonexistent parent collections, newspapers, newspaper issues, or books), and allows someone with appropriate permissions to delete them. Includes new permission (Manage orphaned objects).
PR at request of @rosiel, duplicating the functionality of the [Orphaned Objects module
](https://github.com/bondjimbond/islandora_orphaned_objects)
- Generates a list of all orphaned objects
- Creates new permission to manage orphaned objects
- Allows admin to selectively or batch delete via the list
Create some orphaned objects...
- From a Collection Manage screen, delete children that contain children (e.g. newspapers, books, collections that have children …

Add orphaned objects capability to core

---

.travis.yml
includes/manage_deleted_objects.inc
includes/orphaned_objects.inc

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2178
Adds namespace and XACML filters to the manage deleted objects page.
Also a bunch of formatting stuff.
Create 2 objects with the same content-model (say basic image) and different namespaces (ie. `foo:` and `bar:`). Set them to `Deleted` on the manage properties tab.
Go to the `Manage Deleted Objects` page (under Admin -> Islandora )
Choose the content-model you used and you should see both items available for purging.
Go to Admin -> Islandora -> Configuration and enable namespace restrictions and only add `foo:` to the allowed namespaces.
Go back to the `Manage Deleted Objects` page. You can still purge both objects.
Pull in this PR and go to `Manage Deleted Objects`, you should no longer see the `bar:` namespaced object. …

Respect namespace restrictions in manage deleted objects.

---

includes/datastream.inc

I'm seeing this in my logs: 
```
Error: Call to a member function getTimestamp() on boolean in islandora_view_datastream_cache_check()
```
This checks that [DateTime::createFromFormat](http://php.net/manual/en/datetime.createfromformat.php) didn't return a boolean.
Should prevent warnings in logs from `islandora_view_datastream_cache_check()`
* Check warnings before
* Check no warnings after
@DiegoPino

Prevent Warning

---

includes/datastream.inc
islandora.api.php

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1748
Adds an alter hook that permits modules to change the file names of downloaded datastreams.
Background:
* The islandora_datastream_filenamer module allows the file names of downloadable datastreams to be modified, using tokens such as the object pid, datastream id, etc.
* But in order to work, it requires a patch be applied to islandora core.
This change addresses the need by:
* Creates a new drupal_alter hook in islandora/includes/datastream.inc: hook_islandora_datastream_filename_alter().
* Documents the hook in islandora.api.php
* Implement hook_islandora_datastream_filename_alter in a module. This could do anything to modify the filename, e.g. add "test-" to the beginning.
* Test to see if, when downloading any …

ISLANDORA-1748 -- add hook_islandora_datastream_filename_alter().

---

README.md
includes/admin.form.inc

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2215
Adds a configuration screenshot to the Islandora README, and mentions the new permission relating to inactive/deleted objects. It also improves the wording on the admin form as suggested by @bencomp. 
* Readme differs
* Admin form has new description
View the revised readme at my fork: https://github.com/rosiel/islandora-1/tree/7.x-documentation
* Does this change require documentation to be updated?  * Screenshot on the wiki's also very out of date - will update when this change is accepted. https://wiki.duraspace.org/display/ISLANDORA/Islandora+Core+Module
* Does this change add any new dependencies?  no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* …

ISLANDORA-2215 Documentation of new permission and add screenshot to README.

---

README.md
includes/admin.form.inc

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2215
** Sister PR on 7.x:** #707 
Adds a configuration screenshot to the Islandora README, and mentions the new permission relating to inactive/deleted objects. It also improves the wording on the admin form as suggested by @bencomp. 
* Readme differs
* Admin form has new description
View the revised readme at my fork: https://github.com/rosiel/islandora-1/tree/7.x-documentation
* Does this change require documentation to be updated?  * Screenshot on the wiki's also very out of date - will update when this change is accepted. https://wiki.duraspace.org/display/ISLANDORA/Islandora+Core+Module
* Does this change add any new dependencies?  no
* Does this change require any other modifications to be made to the repository (ie. …

7.x 1.11 documentation

---

includes/datastream.version.inc

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2359
`form_load_includes` the file that the form itself is in which can become out of scope on AJAX rebuilds.
`form_load_include`ing a file.
Replace datastream contents, nothing obvious changes.

Form_load_include the file.

---

.github/PULL_REQUEST_TEMPLATE.md

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2349
Two changes to the pull request template:
1. New text at the top to warn the unwary to not leave all of the default text in place when submitting a pull request. Lots of !!!! and CAPS because it has to be noticeable in the *edit* screen, not when published.
1. Expanding the "does this need documentation" text to include examples and cut down on false negatives.
This was discussed at the November 29th Committers call. The change about documentation was uncontroversial. The warning is more of a trial for discussion, and I wonder a little if the cure isn't more trouble than the disease. Would we rather have the occasional pull request full of dud template language, or a big flashy warning for everyone to scroll past? Anyway, …

ISLANDORA-2349 Changes to pull request template

---

tests/scripts/travis_scripts.sh

**JIRA Ticket**: no JIRA, work related to #714 
While working on Solr Search I discovered that I needed a custom ignore to skip the `SolrPhpClient` directory. This should allow a module to export a custom `CODESNIFFER_IGNORE` if it needs it but otherwise falls back to the default.
Travis should still pass for Islandora to ensure that the default is taking effect, the opposite case will be tested when I open a PR on islandora_solr_search.
Example:
* Does this change the interface, add a new feature, or otherwise change behaviours that would require updating documentation? no
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing …

Allow custom codesniffer ignore arguments

---

.travis.yml
README.md
includes/tuque_wrapper.inc
islandora.install
islandora.module

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2424
Allows PHP 5.3.3. to fail in Travis without marking the build as a failure.
Travis with test
* Does this change the interface, add a new feature, or otherwise change behaviours that would require updating documentation? no
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? no

Allow PHP 5.3.3 to fail

---

README.md

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2444
* Other Relevant Links: https://wiki.duraspace.org/display/ISLANDORA/Start
I received feedback from the audience at an Islandora session at OR2019 that a way to find the modules developed by our community would be really helpful. This [exists](https://github.com/Islandora-Labs/islandora_awesome), but clearly it needs to be easier to find. 
This adds a link with a brief description. There's a similar addition on the [front page](https://wiki.duraspace.org/display/ISLANDORA/Start) of the user wiki docs.
One new line in the readme.
Verify that wording is clear; test that the link resolves.
@DonRichards as Documentation Manager for 7.x-1.13, do you want to have a look at this?

 ISLANDORA-2444 Update readme with Awesome link

---

islandora.module

**JIRA Ticket**: [ISLANDORA-2443](https://jira.duraspace.org/browse/ISLANDORA-2443)
Add missing datastream paths to the `hook_admin_paths` implementation.
Added `replace` and `delete` datastream paths to the list of administrative paths. Updated `version` path to catch all the version paths.
Ensure that the following paths are being treated as admin paths (i.e. using the admin theme in lieu of any custom theme):
`/islandora/object/{object}/datastream/{datastream}/replace`
`/islandora/object/{object}/datastream/{datastream}/delete`
`/islandora/object/{object}/datastream/{datastream}/version`
`/islandora/object/{object}/datastream/{datastream}/version/{version_num}/view`
`/islandora/object/{object}/datastream/{datastream}/version/{version_num}/revert`

Add more datastream paths as admin paths

---

tests/scripts/travis_scripts.sh
theme/islandora-object.tpl.php

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2424
Stop running code sniffer via coder-review, we run phpcs separately right after this.
This is specifically because the newer versions of coder-review do not seem to respect the `// @codingStandardsIgnoreStart`, `// @codingStandardsIgnoreFile`, or `// phpcs:ignoreFile`  statements
This is the reason that https://github.com/Islandora/islandora_solr_search/pull/359 can't pass due to SolrPhpClient.
An alternative solution would be to make the set of checks customizable, but then we could have a changing set of checks per module.
Remove the `style` check and leave the others.
Things that pass should still pass, things that would fail on a style check here should fail on phpcs.
I am out of ideas on this one (specifically …

Stop running "style" coder check

---

.gitignore
composer.json

**JIRA Ticket**: None, I be de-CLAWing Islandora 8
Packagist is rejecting `islandora/islandora` because 7.x doesn't have a `composer.json` file.  I'm testing the waters here with a dummy file just to see if it will appease our packagist overlords.  In theory, packagist just ignores branches without composer.json files, so I'm wondering if it's because 7.x is the default branch.  But switching that to 8 would be pretty disruptive and I'd rather give folks a heads up with time to prepare in case it messes with their builds.  For example, `islandora_vagrant` would be affected by this and need to be updated.  So I'm trying this first :laughing: 
The most bare-bones composer.json file humanly possible.
A kind soul merges this and packagist is appeased... or not.  In that case, we'll revert. …

Dummy composer.json to see if it'll appease packagist

---

.travis.yml

**JIRA Ticket**: https://github.com/Islandora/documentation/issues/1267
Tests on 7.2 and 7.3, which we should do everywhere.  Hence I'm adding this as part of the CLAWdit.

Testing PHP 7.2 and 7.3

---

src/Plugin/ContextReaction/JsonldSelfReferenceReaction.php
tests/src/Functional/JsonldSelfReferenceReactionTest.php
tests/src/Functional/JsonldTypeAlterReactionTest.php

Originally from @rosiel.  Can't take any credit for this one!  Migrated over from Islandora-CLAW/islandora.
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1303
To channel @seth-shaw-unlv , 🎶 If I go there's just no telling how far I'll go 🎶
*  Per Eli's and my diagram, this is how we put (excuse the lazy rdf) `<node/1> schema:sameAs <node/1>` in the JSON-LD of node/1,  in order to have `<fedoraURI> schema:sameAs <node/1>`. The schema:sameAs is the "Drupal URI Predicate" in the "Map Drupal URI to Predicate" reaction. Those labels, alone, do not explain what's going on.
Renames almost all uses of "Map URI to predicate"-type wording into "JSON-LD Self-Reference Predicate"-type wording.
Front-end: 
* Renames the Reaction's human-readable label to "JSON-LD self-reference".
* …

Drupal uri predicate

---

islandora.module
modules/islandora_core_feature/config/install/field.storage.media.field_original_name.yml

**Github Issue**: https://github.com/Islandora/documentation/issues/1276
Adds the PREMIS 3 namespace and creates the field storage for an 'original name' field for media.
- Apply this PR
- Apply https://github.com/Islandora/islandora_defaults/pull/13
- Import both the Islandora Core and Islandora Defaults features. E.g. `drush fim -y islandora_core_feature; drush fim -y islandora_defaults`
- Create a Media; you should see an 'Original Name' field. Plop any text you want in there.
- View the Media's JSON-LD; you should see the text from the original name field associated with the PREMIS 3 originalName predicate
- View the Media in Fedora; the PREMIS 3 originalName value should be there too.
We should eventually figure out how to auto-populate this from the file upload widget.
@mjordan, …

Add 'Original Name' field storage

---

islandora.module
theme/theme.inc

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2480
* Related PR: #726  
Add optional label text to datastream download links
* Adds optional `label` argument to `theme_islandora_datastream_download_link()`
Use `islandora_datastream_download_link()` in a theme, e.g. to add the ability to download the PDF of book or newspaper content. Use the `label` argument to provide text for the link.

Add optional label text to datastream download links

---

theme/theme.inc

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2479
Fixes `theme_islandora_datastream_view_link()` to include the correct file. Additionally, improves the safety of the code.
* Replaces erroneous include of `includes/utilities` with `includes/datastream`. 
* Replaces `=== NULL` checks with `isset()`. 
* Adds `$version` variable, rather than passing `$vars['version']`
Use `islandora_datastream_view_link()` in a theme, e.g. to add the ability to view the PDF of book or newspaper content.
@Islandora/7-x-14-committers

Fix theme_islandora_datastream_view_link()

---

src/EventGenerator/EventGenerator.php

All work done by @elizoller.  Can't take any credit on this one.  I just migrated this PR over from https://github.com/Islandora-CLAW/islandora/pull/154
**GitHub Issue**: Related to: (https://github.com/Islandora-CLAW/CLAW/issues/740)
* Allows versioning of an object to be initiated from Drupal node updates
* Adds a context action create_node_version_in_fedora which can be added to a context reaction.
* Adds the event type to the event object being passed to Alpaca
* Adds a "Version" event type
* This change could be added to the index "reaction" in the repository item context by default and/or added to documentation that this is how one "enables" versioning on a node
* pull in the PR to your islandora modules - uninstall/re-enable islandora_core_feature
* add the "Create Node Version in …

Versioning

---

src/Commands/IslandoraCommands.php

**GitHub Issue**: https://github.com/Islandora/documentation/issues/1322
Adds the userid option to the Drush migrate:rollback command.
* pulls validating the option, switching the user, and switching the user back into separate functions.
* modifies the existing functions to call the generalized ones.
* adds new functions to implement the hooks for rollback.
* Does this change require documentation to be updated? No. 
* Does this change add any new dependencies? No.
* Does this change require any other modifications to be made to the repository
(i.e. Regeneration activity, etc.)? No.
* Could this change impact execution of existing code? No.
* Try to rollback a migration using the drush command; you won't see a message about user switching and, even if you don't get an error, Fedora won't …

Add userid option to migrate:rollback

---

islandora.module
tests/src/Functional/JsonldSelfReferenceReactionTest.php
tests/src/Functional/JsonldTypeAlterReactionTest.php

**Github Issue**: https://github.com/Islandora/documentation/issues/1379
Fixes tests by changing how we invalidate caching with our jsonld alters... and nudging the tests a little.
I add some cache tags to the `$context['cacheability']` metadata provided in the alter function.
Before this PR:
* View a node's jsonld, it probabaly has `schema:sameAs` with the Drupal URL in there.
* Go edit the `Content` context and change the self reference URL to `owl:sameAs`.
* View the node's jsonld again, but you don't see `owl:sameAs`.  It's still `schema:sameAs`!
After this PR:
* View a node's jsonld, it probabaly has `schema:sameAs` with the Drupal URL in there.
* Go edit the `Content` context and change the self reference URL to `owl:sameAs`.
* View the node's jsonld again, and you'll see …

Jsonld alter caching

---

config/schema/islandora.schema.yml
src/IslandoraUtils.php
src/Plugin/Condition/MediaHasTerm.php
src/Plugin/Condition/NodeHasTerm.php
src/Plugin/Condition/ParentNodeHasTerm.php
src/Plugin/EntityReferenceSelection/ExternalUriSelection.php
tests/src/Functional/NodeHasTermTest.php

**JIRA Ticket**: Resolves https://github.com/Islandora/documentation/issues/1337
Also part of https://github.com/Islandora/documentation/issues/1325
Adds AND/OR radio buttons to `NodeHasTerm` and children classes.
- Pull in this PR
- Clear your cache
- Go see a NodeHasTerm condition in the context UI and check out its sweet functionality
- Try it with both AND and OR to see if both work appropriately.
- Also try it with negation, since that's a thing we've been doing incorrectly recently.

Adding OR logic to NodeHasTerm and ilk

---

src/ContextReaction/DisplayAlterReaction.php
src/Controller/ManageMembersController.php
src/EventGenerator/EmitEvent.php
src/EventSubscriber/LinkHeaderSubscriber.php
src/Form/IslandoraSettingsForm.php
src/IslandoraUtils.php
src/MediaSource/MediaSourceService.php
src/Plugin/Action/AbstractGenerateDerivative.php
src/Plugin/Action/EmitFileEvent.php
src/Plugin/Action/EmitMediaEvent.php
src/Plugin/Condition/FileUsesFilesystem.php
src/Plugin/Condition/MediaHasMimetype.php
src/Plugin/Condition/MediaUsesFilesystem.php
src/Plugin/Condition/NodeHadNamespace.php
src/Plugin/Condition/NodeHasParent.php
src/Plugin/Condition/NodeHasTerm.php
src/Plugin/Condition/NodeIsPublished.php

**Github Issue**: https://github.com/Islandora/documentation/issues/1361
Replaces type hints in constructors to use interfaces instead of implementing classes.
In constructors, you should see the following values replaced:
- `EntityTypeManager` -> `EntityTypeManagerInterface`
- `EntityFieldManager` -> `EntityFieldManagerInterface`
- `FileSystem` -> `FileSystemInterface`
- `Token` -> `TokenInterface`
Nothing should break.  @qadan should be able to use webprofiler?
@Islandora/8-x-committers @qadan

Injecting interfaces instead of actual classes

---

islandora.module
tests/src/Functional/JsonldSelfReferenceReactionTest.php

**JIRA Ticket**: https://github.com/Islandora/documentation/issues/1412
This adds the prefix `dcterms` to the module mapping. Note that this prefix is a duplicate of the `dc` prefix that drupal defines. They both point to `http://purl.org/dc/terms/`. (drupal doesn't have a prefix for dc elements - hence islandora.module defining `dc11` pointing to that.)
The reason I'm adding this is because the prefix `dcterms` is used in the rdf mappings in islandora_defaults.  There's a bigger question of whether or not we should use `dc` or `dcterms`, but for now this fixes the issue see in the above ticket. 
This is almost a one liner to add the `dcterms` prefix and a tweak to the test code to use `dcterms` instead of `dc` -  that change is questionable and I can take it out if desired.
Example:
* …

Adds prefix for dcterms to module

---

modules/islandora_breadcrumbs/src/IslandoraBreadcrumbBuilder.php

**Github Issue**: https://github.com/Islandora/documentation/issues/1430
Adds a 'Home' link to the breadcrumbs generated by the islandora_breadcrumbs submodule.
Simply adds a single line to the module to include a 'Home' link to the breadcrumbs.
- Create a collection and a child of that collection (sub-collection, image, whatever...)
- Visit that child's page and breadcrumbs will appear without a 'Home' link.
- Apply the PR
- Clear cache
- Visit the child's page again and the breadcrumbs will appear with a 'Home' link (appropriately translated to your site's language settings).
N/A
@Islandora/8-x-committers + @wgilling

add Home link to breadcrumbs

---

composer.json
islandora.info.yml

**JIRA Ticket**: Resolves https://github.com/Islandora/documentation/issues/1309 and https://github.com/Islandora/documentation/issues/1366
Pulls in `drupal/transliterate_filenames` to sanitize file names on upload.
A new dependency, that's it.  Requires no config or special installation steps.

Adds suggestion for drupal/transliterate_filenames

---

src/Plugin/Condition/EntityBundle.php
src/Plugin/Condition/MediaHasMimetype.php
src/Plugin/Condition/NodeHadNamespace.php
src/Plugin/Condition/NodeHasParent.php
src/Plugin/Condition/NodeIsPublished.php

**Github Issue**: Resolves https://github.com/Islandora/documentation/issues/1325
Stops doing negation logic in our Condition plugins so they can be negated downstream.
Less checks using `isNegated()`.
Pull down the PR and set up contexts using these Conditions to do something simple like switch themes:
- `EntityBundle`
- `MediaHasMimetype`
- `NodeHadNamespace`
- `NodeHasParent`
- `NodeIsPublished`
The contexts should behave as expected both normally and when negated.
@Islandora/8-x-committers @qadan

No longer double negating conditions

---

modules/islandora_core_feature/config/install/field.storage.media.field_media_document.yml

**GitHub Ticket**: https://github.com/Islandora/documentation/issues/1459
See also https://github.com/Islandora/islandora_defaults/pull/26
Makes the new Document media type default storage location set to Fedora as the other media type files are.
* Added field_media_document storage config
*Test in conjunction with https://github.com/Islandora/islandora_defaults/pull/26*
- Create a new document media and upload a file. _Should upload to Drupal public._
- Apply the PR
- Import `islandora_core_feature` feature.
- Create a new document media and upload a file. _Should upload to Fedora via flysystem._
* Does this change the interface, add a new feature, or otherwise change behaviours that would require updating documentation? Adds Document media files to Fedora as the other media types …

Save document media files to fedora by default (Issue-1459)

---

src/Plugin/Action/AbstractGenerateDerivative.php

**GitHub Issue**: (link)
https://github.com/Islandora/documentation/issues/1475
Supercedes withdrawn PR https://github.com/Islandora-CLAW/islandora/pull/181
Fixes a check for `$derivative_term` after it has been fetched by URI.
Should trap cases where a derivative term can't be located by URI.
* Add a Repository Item with Model=Image
* Add media, type=Image, Use=Original Term
* When media is submitted, and derivatives generated, you might see an error message "Error generating event: Could not locate derivative term with urihttps://projects.iq.harvard.edu/fits"
@Islandora-CLAW/committers

#1475 Check derivative_term instead of source_term

---

modules/islandora_text_extraction/islandora_text_extraction.module
modules/islandora_text_extraction/islandora_text_extraction.services.yml
modules/islandora_text_extraction/src/SearchReindexer.php

**JIRA Ticket**: Resolves https://github.com/Islandora/documentation/issues/1476
Manually triggers search re-indexing for nodes when their extracted text media are inserted or updated.
Brute forcing re-indexing in media insert and update hooks.
- Ingest some paged content
- Go to a page and look at its extracted text file
- Search for something in the text
- Should get no results
Now apply this PR
- Ingest a new page
- Go to the page and look at its extracted text file
- Search for something in the text
- Should get results!

Fixes Extracted Text not indexing in solr

---

modules/islandora_text_extraction_defaults/config/install/rdf.mapping.media.extracted_text.yml
src/Plugin/ContextReaction/JsonldTypeAlterReaction.php

**JIRA Ticket**: Resolves https://github.com/Islandora/documentation/issues/1477
Adds an RDF mapping for extracted text media.  Also touches up the JsonldTypeAlterReaction so it doesn't WSOD if there's ever another missing RDF mapping.
- Visit the `?_format=jsonld` endpoint for an extracted_text media.
- You'll WSOD
- Apply this PR
- `drush -y fim islandora_text_extraction_defaults`
- Visit the `?_format=jsonld` endpoint again
- No WSOD

Fixes JSONLD endpoint fail for Extracted Text

---

modules/islandora_text_extraction/islandora_text_extraction.module

**Github Issue**: https://github.com/Islandora/documentation/issues/1479
Slack: https://islandora.slack.com/archives/CM5PPAV28/p1585769436179000
When updating an Extracted Text, instead of checking for the existence of a value in `field_edited_text` it checks to see if it matches the contents of the file.
* Changes checking extracted text media from the existence of a value in `field_edited_text` to matching the contents of the file.
- Replace the Original File of a Page (or Digital Document) node with text content with one with different text.
- Check the Extracted Text file to see the new text content and then see if the contents of `field_edited_text` matches. (It won't.)
- Apply the PR.
- Run the Extract Text action on the node again.
- The value of the Extracted Text media's …

Fix stale field_edited_text (Issue 1479)

---

islandora.install
src/Plugin/Condition/EntityBundle.php
tests/src/Functional/EntityBundleTest.php
tests/src/Functional/JsonldTypeAlterReactionTest.php

**JIRA Ticket**: Islandora/documentation#1470
Supersedes https://github.com/Islandora/islandora/pull/771
Changes the plugin_id for the entity_bundle Condition to islandora_entity_bundle to avoid a name collision with ctools entity_bundle plugin.
It also has an update hook to update any contexts that may be using the `entity_bundle` condition.
When this patch is applied, it should be possible to install pathauto and ctools and generate url aliases for taxonomy terms in the corporate_body vocabulary.
1. On a fresh install, download & enable pathauto (also brings ctools).
1. Visit /admin/config/search/path/patterns/add and try and specify a pathauto pattern for a corporate_body term, e.g. pattern=`/agent/[term:name]`. Observe "The website encountered an unexpected error. Please try again …

Renames `entity_bundle` to `islandora_entity_bundle` to avoid name collision

---

islandora.links.menu.yml
islandora.routing.yml
src/Controller/RdfMappingsReportController.php
src/IslandoraUtils.php

**Github issue**: https://github.com/Islandora/documentation/issues/1521
Adds a report listing all the 1) configured Drupal-field-to-RDF properties and 2) all of the external URIs associated with taxonomy terms.
* Adds a new controller at `admin/reports/islandora/rdf_mappings` that generates and renders the report
* Updates the `getUriFieldNamesForTerms()` function in the Islandora Utilities service
1. Check out this branch. Within the `islandora` module directory:
1. `git remote add mjordan https://github.com/mjordan/islandora.git`
1. `git fetch mjordan`
1. `git checkout issue-1521`
1. Clear your cache (`drush cr`)
1. Visit Admin > Reports > Field and term RDF mappings (refresh if you don't see this new item)
1. You should see the report listing fields and their RDF property mappings, …

Issue 1521: Provide a way for repo admins to see RDF mappings

---

src/Form/IslandoraSettingsForm.php
src/StompFactory.php

**JIRA Ticket**: https://github.com/Islandora/documentation/issues/1454
Adds user/password configuration for the broker such that non-anonymous connections can be made.
Configuration form settings and passing down the credentials to the `islandora.stomp` service.
Configure ActiveMQ to require authentication.
Add those credentials to the form.
Things operate as expected.

Add configuration for a user and password to the broker.

---

src/Form/IslandoraSettingsForm.php
tests/src/Functional/IslandoraSettingsFormTest.php

**JIRA Ticket**: https://github.com/Islandora/documentation/issues/1498
Tightens allowed time intervals for JWT expiry.
You must have a positive integer, you must use one of the expected time intervals.
It is possible to create some weird strings, but I haven't really tested all the things that `strtotime()` might allow.
Pull in this code and try adding some weird expiry intervals.

Validate JWT expiry

---

modules/islandora_iiif/islandora_iiif.routing.yml

**Github Ticket**:
#1534 Tighten access to Islandora IIIF config form 
https://github.com/Islandora/documentation/issues/1534
Changes config permission for Islandora IIIF config form from 'access administration pages' to 'administer site configuration' so that some roles can have (say) content administration via administration pages without being able to alter key site configuration.
A brief description of what the intended result of the PR will be and/or what problem it solves.
Changed permission for `/admin/config/islandora/iiif`
With a user role with 'access administration pages' permission note that /admin/config/islandora/iiif is accessible. With this patch they should get "You are not authorised to access this page.", and 'administer site configuration' is required instead. …

#1534 Change config permission to 'administer site configuration'

---

modules/islandora_breadcrumbs/src/IslandoraBreadcrumbBuilder.php

**Github Ticket**: https://github.com/Islandora/documentation/issues/1559
Resolves an issue where deleting an item in the member_of chain throws an Exception with a WSOD when attempting to view a child of that chain.
Adds a check to the islandora breadcrumbs builder to ensure the next step in the member_of chain _is_ actually an entity (e.g. wasn't deleted).
- Create a collection with a child object.
- View the child and clear the cache to ensure the breadcrumbs appear.
- Delete the parent collection.
- Revisiting the child shows a WSOD.
- **Apply the PR**
- View the child object (no WSOD). 
- _You can also recreate the collection, add the child, and delete the collection again if you want to double-check._
Credit for this fix goes to @ainsofs who [posted the patch to the original …

Issue-1559: Fix breadcrumbs error when part is deleted

---

islandora.install

**Github Issue**: Resolves https://github.com/Islandora/documentation/issues/1528
Gets rid of the `islandora_version_count` table, b/c we never implemented the two-way sync.
I removed `hook_schema` and added an update hook to remove the table. :fire: :fire: :fire:
- Pull down this pr
- `drush updb`
` `drush sql:cli` and then `show tables`
- `islandora_version_count` should not be in the list.

Removing isladora_version_count table

---

modules/islandora_iiif/src/Plugin/views/style/IIIFManifest.php

**Github Issue**: https://github.com/Islandora/documentation/issues/1568
Adds `ConnectException` to the list of exceptions we try to catch when calling out to Cantaloupe to make a IIIF manifest.
Just another exception in the try/catch.  I combined all the `catch`es and also nested the fallback code within the catch block for cleanliness.
- Shut down cantaloupe
- Try to view a IIIIF manifest for a piece of paged content
- You should get a WSOD
- Apply this PR
- `drush cr`
- Try to view a IIIIF manifest for a piece of paged content again
- No whitescreen.  We fall back to pulling info out of Drupal metadata.
@Islandora/8-x-committers @DonRichards @nigelgbanks

Handling case where IIIF manifest generation fails if cantaloupe is down

---

src/Controller/RdfMappingsReportController.php

**Github issues**: https://github.com/Islandora/documentation/issues/1549 and https://github.com/Islandora/documentation/issues/1550.
Adds bundle-to-RDF-Type mapping and multiple predicate values.
For fields that are mapped to multiple properties, all are now showing up, not just the first. For bundles, their mapping to RDF Type are now displayed.
1. Pull in this branch.
1. Visit `admin/reports/islandora/rdf_mappings`
1. Confirm that multi-property fields are showing all the expected mappings (e.g. "Name (name)" in the Audio media bundle)
1. Confirm that bundle-to-RDF-Type mappings are showing up as expected next to the bundle names/labels like in this screenshot:
* Does this change the interface, add a new feature, or otherwise change behaviours that would require updating documentation? …

Work on #1549 and #1550.
